# Generated by Django 4.2.7 on 2023-11-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
